<h4>EKG</h4>
<table class="identity-header">
    <tbody>
        <tr>
            <td>
            	<table>
		            <tr>
		                <td>Irama</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Rate</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Axis</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Kelainan</td>
		                <td></td>
		            </tr>
		        </table>
            </td>
            <td>
         		<table>
		            <tr>
		                <td>Kesimpulan</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Saran</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Abnormal</td>
		                <td></td>
		            </tr>
		            <tr>
		                <td>Pemeriksa</td>
		                <td></td>
		            </tr>
		        </table>
            </td>
        </tr>
    </tbody>
</table>

